version: "3.7"

services:
  database:
    image: postgres
    container_name: partyrent_db
    restart: always
    ports:
      - 5460:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=partyrent
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local